version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - .:/django_cms
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    tty: true
    environment:
      - DEBUG=1


