version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8088"
    volumes:
      - ./django_cms:/django_cms
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1


