# Generated by Django 3.1.7 on 2021-05-12 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210330_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimebasedData',
        ),
    ]
