# Generated by Django 3.1.7 on 2021-03-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimebasedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=60)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('typ', models.CharField(max_length=60)),
            ],
        ),
    ]
