# Generated by Django 3.1.7 on 2021-03-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebaseddata',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
