# Generated by Django 3.1.7 on 2021-05-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataQuelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(default='localhost:8083', max_length=100)),
                ('protokol', models.CharField(default='mqtt', max_length=10)),
                ('variable_address', models.CharField(default='/test/sin', max_length=100)),
                ('variable_name', models.CharField(default='strom', max_length=100)),
            ],
        ),
    ]
