# Generated by Django 3.1.7 on 2021-05-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacollection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataquelle',
            name='protocol',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='dataquelle',
            name='server',
            field=models.CharField(default='', max_length=100),
        ),
    ]
